name: Build and Deploy ASP.NET App

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: 'SICI-ASP'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Construye la aplicaci贸n
    runs-on: ubuntu-latest
    steps:
      - name: Recupera el c贸digo fuente
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Construir la aplicaci贸n
        run: dotnet build --configuration Release --no-restore --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publicar la aplicaci贸n
        run: dotnet publish --configuration Release --no-build --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
